event_inherited();

// Skins
skin_name = translate_get("CharactersStyles.Echo");
frame = spr_fell_sans_echo_frame;

// Animations
idle_animation = spr_fell_sans_echo_idle;
after_battle_animation =  spr_fell_sans_echo_idle;
defeated_animation =  spr_fell_sans_echo_defeated;
defeated_animation_last_image = spr_fell_sans_echo_defeated_last_image;

hand_up_animation = spr_fell_sans_echo_attack_2_up;
hand_down_up_animation = spr_fell_sans_echo_attack_2_down_up;
hand_left_up_animation = spr_fell_sans_echo_attack_2_left_up;
hand_right_up_animation = spr_fell_sans_echo_attack_2_right_up;
hand_down_animation = spr_fell_sans_echo_attack_2_down;
hand_up_down_animation = spr_fell_sans_echo_attack_2_up_down;
hand_left_down_animation = spr_fell_sans_echo_attack_2_left_down;
hand_right_down_animation = spr_fell_sans_echo_attack_2_right_down;
hand_left_animation = spr_fell_sans_echo_attack_2_left;
hand_up_left_animation = spr_fell_sans_echo_attack_2_up_left;
hand_down_left_animation = spr_fell_sans_echo_attack_2_down_left;
hand_right_left_animation = spr_fell_sans_echo_attack_2_right_left;
hand_right_animation = spr_fell_sans_echo_attack_2_right;
hand_up_right_animation = spr_fell_sans_echo_attack_2_up_right;
hand_down_right_animation = spr_fell_sans_echo_attack_2_down_right;
hand_left_right_animation = spr_fell_sans_echo_attack_2_left_right;