time_source_destroy(time_source_update);
time_source_destroy(time_source_cooldown);
time_source_destroy(time_source_update_tentacles);
time_source_destroy(time_source_update_shot);
time_source_destroy(time_source_update_destroy);
