/// @desc Set font
set_font("Ink", "", global._font_main_comic_sans, c_white);
set_font("Sans", "", global._font_main_comic_sans, c_sans);
set_font("C", "", global._font_main_determination, c_white);
set_font("XChara", "", global._font_main_determination, c_white);
set_font("XCharaSpirit", "", global._font_main_determination, c_white);
set_font("CrossXEvent", "", global._font_main_comic_sans, c_white);
set_font("Error", "", global._font_main_comic_sans, c_error);
set_font("Papyrus", "", global._font_main_papyrus, c_white);
set_font("Nightmare", "", global._font_main_comic_sans, c_nightmare);
set_font("Dream", "", global._font_main_comic_sans, c_orange);