time_source_destroy(time_source_update);
time_source_destroy(time_source_update_bone);
time_source_destroy(time_source_update_bone_1);
time_source_destroy(time_source_update_platforms);
time_source_destroy(time_source_update_destroy);

