time_source_destroy(time_source_update);
time_source_destroy(time_source_bone_update);
time_source_destroy(time_source_update_tentacles);
time_source_destroy(time_source_update_destroy);

final_function();