/// @description Story mode animations end

// Episode 1

change_sprite_to_other_sprite(spr_sans_idle_looking_up, spr_char_sans_idle);

// Episode 3

change_sprite_to_other_sprite(spr_sans_sitting_putting_steak, spr_sans_sitting_put_steak);
change_sprite_to_other_sprite(spr_sans_volleybro_flies_away_from_ball, spr_sans_volleybro_flying_away);
change_sprite_to_other_sprite(spr_sans_volleybro_falls_from_ball, spr_sans_volleybro_fell_from_ball);
change_sprite_to_other_sprite(spr_sans_volleybro_stands_up_after_fall, spr_sans_volleybro_standing_without_bandana);
change_sprite_to_other_sprite(spr_sans_volleybro_taking_jacket, spr_sans_volleybro_standing_right_with_jacket);