/// @description Story mode animations end

// Epidode 1

change_sprite_to_other_sprite(spr_char_ink_sans_flip, spr_char_ink_sans_attack_fight);
change_sprite_to_other_sprite(spr_char_ink_sans_attack_finish, spr_char_ink_sans_calm);

// Episode 2

change_sprite_to_other_sprite(spr_ink_sans_pukes, spr_ink_sans_puked);
change_sprite_to_other_sprite(spr_ink_sans_flying_distracting, spr_ink_sans_flying_distracted);
change_sprite_to_other_sprite(spr_ink_sans_pukes, spr_ink_sans_puked);
change_sprite_to_other_sprite(spr_ink_sans_flying_throwing_stuff, spr_ink_sans_flying_threw);
change_sprite_to_other_sprite(spr_ink_sans_sits_down, spr_ink_sans_sitting_takes_notebook);
change_sprite_to_other_sprite(spr_ink_sans_sitting_takes_notebook, spr_ink_sans_sitting_with_notebook);
change_sprite_to_other_sprite(spr_ink_sans_attack_flying_hit, spr_ink_sans_attack_episide2);
change_sprite_to_other_sprite(spr_ink_sans_left_down_getting_broomie, spr_ink_sans_left_down_got_broomie);
change_sprite_to_other_sprite(spr_ink_sans_left_down_drawing_on_ground, spr_ink_sans_left_down_drew_on_ground);
change_sprite_to_other_sprite(spr_ink_sans_left_down_teleporting, spr_ink_sans_inks_after_teleporting);

// Episode 3

change_sprite_to_other_sprite(spr_ink_sans_appearance_from_inks, spr_ink_sans_standing_left);