event_inherited();

skin_name = translate_get("CharactersStyles.Standard");
frame = spr_dream_sight_dreams_frame;

// Animations
idle_animation = spr_dream_sight_dreams_idle;
after_battle_animation = spr_dream_sight_dreams_idle;
defeated_animation = spr_dream_sight_dreams_defeated;
fight_0_start_animation = spr_dream_sight_dreams_star_rod_start;
fight_0_idle_animation = spr_dream_sight_dreams_star_rod_idle;
fight_0_finish_animation = spr_dream_sight_dreams_star_rod_finish;
fight_1_start_animation = spr_dream_sight_dreams_blades_start;
fight_1_idle_animation = spr_dream_sight_dreams_blades_idle;
fight_1_finish_animation = spr_dream_sight_dreams_blades_finish;
fight_2_start_animation = spr_dream_sight_dreams_bow_start;
fight_2_idle_animation = spr_dream_sight_dreams_bow_idle;
fight_2_finish_animation = spr_dream_sight_dreams_bow_finish;