instance_destroy(charge_object);
time_source_destroy(time_source_flying);
time_source_destroy(time_source_charging);
time_source_destroy(time_source_target);
time_source_destroy(time_source_destroying);