export enum statusCode {
  error = 0,
  success = 1,
  serverSocketClosed = 2,
  databaseError = 300,
  databaseNotConnected = 301,
  databaseDisable = 302,
  databaseAccountNotExists = 303,
  databaseAccountExists = 304,
  databaseProfileNotExists = 305,
  databaseProfileExists = 306,
  databaseUsernameBusy = 307,
  databaseUsernameWrong = 308,
  databasePasswordWrong = 309,
  databaseEmailBusy = 310,
  databaseEmailWrong = 311,
  databaseVerificationWrongCode = 312,
  databaseVerificationTimeout = 313,
  databaseBanExists = 314,
  updateRequired = 426
}
